### ISSUE TITLE
Task - SRS - Reflection

### ISSUE THREAD

**Issue by MitchHynes** [Spitgranger/capstone#109]
**Description**
All team members to put an item into the reflection
**Definition of Done**

- [x] Mitchell
- [x] Richard
- [x] Kyle 
- [x] Rafeed 
- [x] Akshit

**Comment by kyle4908** [comment]
It looks like our reflection questions are out of sync with what we're supposed to answer https://gitlab.cas.mcmaster.ca/courses/capstone/-/issues/3. I'll make a PR to update them.
