### ISSUE TITLE
Action Item - Enroll in Avenue Group

### ISSUE THREAD

**Issue by MitchHynes** [Spitgranger/capstone#11]
All team members to enroll in group 15 on avenue.

**Comment by MitchHynes** [comment]
Update Sept 22: Kyle and Mitchell have enrolled in Avenue group. Removed from assignees list, item still open for other group members.

**Comment by Spitgranger** [comment]
Completed by Richard.

**Comment by RafeedIqbal** [comment]
Joined the group on avenue.

**Comment by akshitg3** [comment]
Completed by Akshit.
