### ISSUE TITLE
Stakeholder Kick-off Meeting - 24/09/2024

### ISSUE THREAD

**Issue by MitchHynes** [Spitgranger/capstone#12]
**Tuesday Sept 24, 10:00 - 11:30 AM**

**Attendance**

- [x] Mitchell 
- [x] Richard
- [x] Akshit (virtually)
- [x] Rafeed
- [ ] Kyle, Not Attending due to scheduling conflict

Team members are to carpool to the location with Mitchell.

**Agenda**

- Meeting to begin with introductions of team members to stakeholders from the City. 
- Mitchell to begin the discussion with a powerpoint presentation. Presentation to explain who we are, what the capstone is, work our team has done to this point on the problem statement, and expected commitment from the City. Link to presentation is [here](https://mcmasteru365-my.sharepoint.com/:p:/r/personal/hynesm5_mcmaster_ca/Documents/Capstone%20Kick-off%20Meeting.pptx?d=w14c6195c4ff2450390ca2fb951fae5de&csf=1&web=1&e=fm360H).
- Main objective after introductions is to brainstorm problems in order to further develop the scope of the project. Need to emphasize we are not thinking of solutions so much at this point, we specifically need to generate as many problems as we can which we will document and filter through to construct the requirements for the application.

**Questions to Ask**

- For verifying that people are on-site, does this require a picture? Or would using GPS location from the device be fine?
- Should every user be able to access all documents, or would some users have different permissions levels? If it is desirable to have different permission levels, is it needed? or just something that would be nice to have?
- Should there be a history of edits made to a file (i.e. keep track of who modified a document and when)? If so, is it needed or nice to have?
- Should documents be versioned (i.e. Allow storage of older versions of files in the system so that people can see the history of what was changed)? if so is it needed or nice to have?
- Are there any existing systems that the client would like this system to be able to integrate with? what might these integrations entail? Are the integrations needed or nice to have?

**Comment by Spitgranger** [comment]
## Meeting Notes for meeting with City of Hamilton Sept 24, 2024

This is a meeting with stakeholders to kickoff the meeting. The goal of this
meeting is to elicit goals and determine the scope of the system. 

### Goals put forward by the city
- Entry protocol, hazard analysis, compliance documentation. Don't want to store
  documents on the site. Should be editable directly remotely.
- The driver of this documentation is regulations.
- to verify completion of work by facilities, don't want to involve operations.
  by having a digital logbook, we just want to know who visited site when, and
what they did.
- Ideally, this information can be exported as an excel document, to show
compliance.
- Don't need to have a contractor portal, there are already initiatives (EAM)?
- Ability to interact with other databases.
- Health and safety tracking (wsib, trainings current, other things).
- Notify if someone who hasn't complete training visits site.
- Complement the physical logbook. Should be able to upload documents to the
system remotely.
- Flag completion red flags if training is not complete.
- It is a bidirectional flow of information.
- Ex. go to site, scan qr code, nfc, takes you to a site that you sign into,
that site has all the hazard assessment documents, they signoff on all that
information on the spot.
- Loading information to stations should be quick. i.e. how to update and upload
  information? Should be easy and quick
- Signoff documents, and 
- Ensure that all inspections are up to date.
- Could be a map where contractors select a station and upload
- Should be a geolocation fencing feature to prove that someone logged in.
- For authentication, use the persons name and email.
- Link workorder, or description of work provided.
- Filter through service categories
- Challenge: contractor is extension of the city, need to keep track of all
their compliance.
- Developing new contracts: don't know when they are on site, what they are
doing on site, keep logs of what work was done, how long the work took, keep of
of stats, ideally export to excel.
- Verify invoices based on time on site.
- ARCOBUS?
    - Asset manager
    - Picture
    - serial numbers
- Note Entry Procedures.
    - Checklist of things to do (e.g. call operators, ppe on?,check that the door is locked, alarm
    disalarmed)
    - can't close work order until that these things have been completed
- Note there is anm interface standard for accessibility standards. (magnify
font, speak, commonly used language)
- Integration with infer (EAM), becos, BI, intellect, mysds, documents shared on
sharepoint, ideally sharepoint will be used to store the documents.
- Integration with coporate security
- Access control: video intercom to process supervisor to request access
(integrate access control logs, live logs?)
- **Emergency alert** in case of shutting down out locking out equipment (maybe
  contractor portal in EAM)
- AIPhone intercom system
- Note: There are some restrictions on collecting some types of data


**Outline**
- Sign in identification (side, building, operations, entry procedures)
- Safety (ppe on)
- Wants to do
    - photo
    - service contract
- Documentation provided from city
- Trained?
- Feedback

**Comment by MitchHynes** [comment]
adding to the above:

- Idea that the system could have "digital keys". Example, an upcoming corporate security keyscanner could be swiped by the phone which authenticates that the user has been granted access for a specific time period.
- City has a "cut sheet" of the video intercom system, can be provided upon request.
